### ISSUE TITLE
Some Bugs found

### ISSUE THREAD

**Issue by DevDokus** [Elemental-RP/ElementalRPServerV1#1]
Hey Guys, great work on this RP server, i looks really nice. 
I did found some bugs, maybe you guys like to know. 

* Twitter is not working on the phone. We are unable to make a account.
* If you buy/rent a house and you enter, you fall through the map instead of entering the house. 
* Behind the building for the DJ there is a green circle that does nothing other then letting you fall trough the map. 
* Hospital inside does not load in, you fall through the map if you enter the hospital.
* Motel: Not able to buy a room. Client side error appears in the console

Hope it help :)

**Comment by SAYREXx** [comment]
> Hey Guys, great work on this RP server, i looks really nice.
> I did found some bugs, maybe you guys like to know.
> 
> * Twitter is not working on the phone. We are unable to make a account.
> * If you buy/rent a house and you enter, you fall through the map instead of entering the house.
> * Behind the building for the DJ there is a green circle that does nothing other then letting you fall trough the map.
> * Hospital inside does not load in, you fall through the map if you enter the hospital.
> * Motel: Not able to buy a room. Client side error appears in the console
> 
> Hope it help :)

"**Base Criada por BlackZon, LikeALord e Sof

Se queres usar esta base terás de fazer algumas modificações, como por exemplo mudar as roupas e carros de cada trabalhos pois usam carros e fardas criadas por nós que não foi publicado.

As roupas, carros e mapas foram retirados a pedido do SOF pois ele teve trabalho a faze-las e nao quer publica-las por agora1

Caso encontres algum erro terás de ser tu a resolver, nós não iremos dar qualquer tipo de suporte**"

**Comment by BlackZon77** [comment]
@DevDokus As you can see there is no files of maps or cars or even clothes.
If you dont have the right map/shells you wont be able to use the house, hospital etc.
The same goes to that green blip behind the DJ building.
In twitter try to check if database of twitter is there.
And motel idk, change motel, that motel is broken and you can dope items.

**Comment by SAYREXx** [comment]
> @DevDokus As you can see there is no files of maps or cars or even clothes.
> If you dont have the right map/shells you wont be able to use the house, hospital etc.
> The same goes to that green blip behind the DJ building.
> In twitter try to check if database of twitter is there.
> And motel idk, change motel, that motel is broken and you can dope items.

Can you sell the version with houses, cars and clothes? Those. full server version?

**Comment by BlackZon77** [comment]
@SAYREXx DM me in discord BlackZon#6298

**Comment by SAYREXx** [comment]
> @SAYREXx DM me in discord BlackZon#6298

Sent request
